### ISSUE TITLE
Can functionality extend into the "ship"?

### ISSUE THREAD

**Issue by ual002** [SingularTier/AerSpeech#18]
How much acsess to game data do you have?  Can a ship diagnostic run-through be created?

Command: "Perform system check"

Hull 78 percent
Thrusters 100 percent
Shield Gen 100 percent
Cargo Hatch 100 percent
Life Support 100 percent
Frame Shift Drive Inoperable

**Comment by ual002** [comment]
If access to that data is limited.  Could a faux "startup sequence" and "Shutdown/standby" command be issued?  Might be neat flair for streamers and immerse gamers.

**Comment by SingularTier** [comment]
No API from frontier yet. It's coming though. This is planned at a much later date.

**Comment by ual002** [comment]
Rgr, thanks.  Sorry again for blowing up the tracker.  I hope this is what its meant for.

**Comment by SingularTier** [comment]
You're doing fine, not a lot of people are using it and I prefer suggestions/bugs here rather than the 2-3 other places I'm getting them from.

I'm closing this for now since the frontier API isn't even announced yet.

**Comment by ual002** [comment]
I figured, the devs for my favorite KSP mods seem to use it alot... Im just afraid to say anything.  Seems too engineery.  But I like it.  All business.
