### ISSUE TITLE
Commodity Data Incomplete or searching is incorrect

### ISSUE THREAD

**Issue by SingularTier** [SingularTier/AerSpeech#2]
Some commodities at stations are not showing up in commodity searches. This can either be because the data from eddb is incorrect or the search is incorrect.

**Comment by SingularTier** [comment]
23:45] <Majkl1> E/I are pointless
[23:45] <Majkl1> I dont even fill those
[23:45] <SingularTier> =\
[23:45] <Majkl1> they are too volatile

**Comment by SingularTier** [comment]
[23:44] <SingularTier> exports/imports are completely wrong
[23:45] <SingularTier> I updated 1 system and gave up
[23:45] <Majkl1> E/I are pointless
[23:45] <Majkl1> I dont even fill those

**Comment by Yona-W** [comment]
Using the full stations.json file could be an optional setting as it might be more complete than the stations-lite.json. The drawback would be, of course, the 100mb file size.

**Comment by SingularTier** [comment]
I'll get the buy/sell data out of the stations.json file. The problem is json.NET drops an OOM exception when trying to parse that 100mb file. I'll have to figure out a way around it.

**Comment by SingularTier** [comment]
Will be fixed in 1.2 release. 

AER now can parse/use the stations.json fill and does a search based on listing data instead of export data.
