### ISSUE TITLE
I may or may not have accidentally forked AerSpeech...

### ISSUE THREAD

**Issue by enenra** [SingularTier/AerSpeech#38]
I'm not sure what to do to make sure I don't delete something I shouldn't by accident - how do I undo this?

**Comment by sutex** [comment]
I'm lost here too,, still trying to work it out,  sure if it bugs someone they'll let you know

**Comment by SingularTier** [comment]
Forking does nothing to my repo. Just delete it =D

**Comment by enenra** [comment]
ok, done!
