### ISSUE TITLE
Calculate Grammar

### ISSUE THREAD

**Issue by SingularTier** [SingularTier/AerSpeech#5]
Voice controlled simple arithmetic so people don't need to open a calculator in the rift.

"Calculate 104.2 [times|multiplied] [by] 10"

**Comment by Yona-W** [comment]
I could take care of this

EDIT: I have a version working with calculations on my fork. I just quickly prototyped it so there isn't exception handling or user-friendly grammar yet so I'm not submitting a pull request, but you can merge it if you want. I'll work on it some more when/if I have time.

**Comment by SingularTier** [comment]
I'll let you handle this, I have a laundry list of things I'm working on. I've opened up some enhancements to let you know what I'm working on.

**Comment by SingularTier** [comment]
I'm going to try and pull in your calcatraz changes before I release 1.3.

1.3 Got accelerated due to a CPU consumption bug (woops, no sleep in polling thread) so yeah.

**Comment by SingularTier** [comment]
I pulled your changes and merged them in to the master branch. 
Thanks a ton for this, works well.
Closing =D
