### ISSUE TITLE
Everything is unknown

### ISSUE THREAD

**Issue by N33t** [SingularTier/AerSpeech#6]
I am using the 1.2 version of the VoiceAttack plugin.
The problem is that AER doesn't know anything, it's like it has no information. If I use the command
"Set current system to <system name>" it responds with "I do not know" no matter what system I say. I have tried both saying system names and spelling them in the nato alphabet. Nothing works. I have manually opened the "/Grammer/Default.xml" file to check that the system names are there, and they are. I have also opened the "Systems.json" to see if the data is actually there, and it is.
I don't know what I am doing wrong. It worked yesterday with the previous version.
Hope you can fix it :)
(btw, this project is AWESOME!)

**Comment by SingularTier** [comment]
I'll take a look.

**Comment by SingularTier** [comment]
Could you give me a list of systems you tried? I know you mentioned 'all of them' but I'm trying to find out if this is a speech engine problem or a grammar problem and narrowing it down to 2-4 systems to test will help.

**Comment by N33t** [comment]
I tried with the following systems
"Sol",
"Artemis",
"Zeus" and
"HIP 103138"
I should also mention that I am on Windows 7 64 bit.
Hope this helps :)

**Comment by SingularTier** [comment]
Sorry, one last thing, could you send me your aer_output.log
%AppData&\Roaming\CMDR Tei Lin\AerSpeech\1.0.0.0\aer_output.log

**Comment by N33t** [comment]
Sure thing.
Hmm, it's kinda empty.
Here is the entire contents:

LOG  : Loading Grammar...

**Comment by SingularTier** [comment]
Woah, what happened to your JSON? Is this standalone or VA plugin?

What is in the Aer\Json folder?

So what's happening is it's not loading the System/Station Data. Which is strange..

**Comment by N33t** [comment]
I am using the VoiceAttack plugin.
When I start VoiceAttack it says 
"Aer initializing" 
And then after a bit it says "I am ready"
My JSON folder contains the following files
Comodities.json, Stations.json, stations_lite.json, stations_test.json, Systems.json
I have not edited this information in any way. I have just downloaded the plugin from your webpage.
Could this be because I am using a trial version of VoiceAttack maybe? (Plus a trial version of the IVONA Ivy voice)

**Comment by N33t** [comment]
Hmm wait a minute. 
The aer_output.log file you wanted is not being updated. I just looked at the timestamp for the file. It was last updated 8/4/2015 at 16:41 local time (GMT+1)
This means that the 1.2 version is not making any log output. At least not for me. I just tried re-downloading the entire AER and putting it into VoiceAttack again. Same result, no information and log file is not being updated. Weird.

**Comment by SingularTier** [comment]
If you're using the VA plugin the  log will be here:
%AppData%\Roaming\VoiceAttack.com\VoiceAttack\1.5.7

Have you tried the standalone version?

Also, thanks for sticking with it. I know it's frustrating =(

**Comment by N33t** [comment]
Ah, I see.
And thank you for actually helping me ^^
I really like this project so I'm just happy to help :)
Anyway, the log file does contain errors. Seems like I'm missing a file or something. Weird since the previous version worked. I also tried downloading the stand-alone version of AER and it works fine. It knows the systems and can retrieve information about them.

Anyway, here is the contents on the log file from the VoiceAttack plugin:

ERROR: Encountered a problem parsing EDDB json files
ERROR: Caught unhandled exception: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
LOG  : Loading Grammar...
LOG  : Initialization Complete.
SPEECH: Start Listening          0,947833895683289
SPEECH: set current system to Sol        0,95066636800766

**Comment by SingularTier** [comment]
Yeah, I was manually packaging the the VA version.

Copy Newtonsoft.Json.dll from the standalone to the VA AER folder it should work. Thanks for sticking with me through this.

I have updated the Release zip.

Let me know if it works and then I will go ahead and close this issue.

**Comment by N33t** [comment]
Ah yes, that worked. Thanks for the help. Sorry it took so long to find such a mundane error.
You are very welcome ^^
Looking forward to the future of this project :)
